### ISSUE TITLE
Error parsing DV_DURATION

### ISSUE THREAD

**Issue by ppazos** [openEHR/archie#113]
The duration values like P0DT1H are not being parsed correctly:

```
de.ehrbase.serialisation.UnmarshalException: Text cannot be parsed to a Period:P0DT1H (through reference chain: com.nedap.archie.rm.composition.Composition["content"]->java.util.ArrayList[1]->com.nedap.archie.rm.composition.Instruction["activities"]->java.util.ArrayList[0]->com.nedap.archie.rm.composition.Activity["description"]->com.nedap.archie.rm.datastructures.ItemTree["items"]->java.util.ArrayList[0]->com.nedap.archie.rm.datastructures.Element["value"]->com.nedap.archie.rm.datavalues.quantity.datetime.DvDuration["value"])
    at de.ehrbase.serialisation.CanonicalJsonTest.obs_inst(CanonicalJsonTest.java:457)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Text cannot be parsed to a Period:P0DT1H (through reference chain: com.nedap.archie.rm.composition.Composition["content"]->java.util.ArrayList[1]->com.nedap.archie.rm.composition.Instruction["activities"]->java.util.ArrayList[0]->com.nedap.archie.rm.composition.Activity["description"]->com.nedap.archie.rm.datastructures.ItemTree["items"]->java.util.ArrayList[0]->com.nedap.archie.rm.datastructures.Element["value"]->com.nedap.archie.rm.datavalues.quantity.datetime.DvDuration["value"])
    at de.ehrbase.serialisation.CanonicalJsonTest.obs_inst(CanonicalJsonTest.java:457)
Caused by: java.lang.IllegalArgumentException: Text cannot be parsed to a Period:P0DT1H
    at de.ehrbase.serialisation.CanonicalJsonTest.obs_inst(CanonicalJsonTest.java:457)
```

This is a snippet of the instance being parsed:

```
               "items": [{
                    "_type": "ELEMENT",
                    "name": {
                        "_type": "DV_TEXT",
                        "value": "duration"
                    },
                    "archetype_node_id": "at0003",
                    "value": {
                        "_type": "DV_DURATION",
                        "value": "P0DT1H"
                    }
                }]
```

**Comment by pieterbos** [comment]
Closing this issue because it is the same as #209 - but that one has a more extensive description, so continuing there.
