### ISSUE TITLE
Archetype parsing raises NullPointerException 

### ISSUE THREAD

**Issue by Yididya** [openEHR/archie#163]
Following the README.md. I tried to parse an ADL file 

```java
String adlFile = "Archetypes/cluster/openEHR-EHR-CLUSTER.ethnischer_hintergrund.v0.adl";
File file = new File(ClassLoader.getSystemClassLoader().getResource(adlFile).getFile());

// Adl file exists
assertThat(file).exists();

ADLParser adlParser = new ADLParser();
Archetype archetype = adlParser.parse(new FileInputStream(file));
```

raises 

```

line 1:23 mismatched input '1.4' expecting VERSION_ID
line 2:1 mismatched input 'openEHR-EHR-COMPOSITION.encounter.v1' expecting ARCHETYPE_HRID

java.lang.NullPointerException
	at com.nedap.archie.adlparser.treewalkers.ADLListener.enterMeta_data_item(ADLListener.java:114)
	at com.nedap.archie.adlparser.antlr.AdlParser$Meta_data_itemContext.enterRule(AdlParser.java:1211)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.enterRule(ParseTreeWalker.java:42)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:25)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
	at com.nedap.archie.adlparser.ADLParser.parse(ADLParser.java:95)
	at com.nedap.archie.adlparser.ADLParser.parse(ADLParser.java:78)
	at de.ukw.openehr.fiddle.TestArchie.testAdl2Parser(TestArchie.java:26)


```
[Test code](https://gitlab2.informatik.uni-wuerzburg.de/YiDoe/openehr-fiddle/-/blob/master/src/test/java/de/ukw/openehr/fiddle/TestArchie.java) can be found here. 

Does _archie_ only work with ADL 2.0?

**Comment by pieterbos** [comment]
Archie works only with ADL 2.0, and it looks like you are parsing an ADL 1.4 archetype. 

However, Archie does include a separate ADL 1.4 parser, that parses ADL 1.4 archetypes into the AOM 2 object model, plus a converter to convert the ADL 1.4 archetypes to ADL 2 archetypes.
The conversion step is necessary to make all of the Archie tools work, since they expect the ADL 2 format. It is possible to use the archetypes without conversion, but no ADL-serialization, flattening or OPT 1.4 support is present without converting it to ADL 2 first.

This converter is documented in the Readme, at https://github.com/openEHR/archie#importing-and-converting-adl-14-files

It is  possible and supported to use reference model data referencing ADL 1.4 archetype structures, including node ids starting with 'at'. This is what the EHRBase project uses, for example.
