### ISSUE TITLE
ArchetypeValidator crashes on missing parentValueSet

### ISSUE THREAD

**Issue by J3173** [openEHR/archie#351]
The ArchetypeValidator crashes when the parent of a value set in a child archetype doesn't exist.

```
ERROR com.nedap.archie.archetypevalidator.ArchetypeValidator - error running validation processor
java.lang.NullPointerException: null
	at com.nedap.archie.archetypevalidator.validations.BasicTerminologyValidation.validateValueSets(BasicTerminologyValidation.java:135)
	at com.nedap.archie.archetypevalidator.validations.BasicTerminologyValidation.validate(BasicTerminologyValidation.java:30)
	at com.nedap.archie.archetypevalidator.ArchetypeValidationBase.validate(ArchetypeValidationBase.java:35)
	at com.nedap.archie.archetypevalidator.ArchetypeValidator.runValidations(ArchetypeValidator.java:230)
	at com.nedap.archie.archetypevalidator.ArchetypeValidator.validate(ArchetypeValidator.java:170)
	at com.nedap.archie.flattener.FullArchetypeRepository.compile(FullArchetypeRepository.java:92)
	at com.nedap.archie.flattener.FullArchetypeRepository.compile(FullArchetypeRepository.java:40)
```

Parent archetype:
```
archetype (adl_version=2.0.5; rm_release=1.0.4)
    openEHR-EHR-OBSERVATION.parent.v1.0.0

language
    original_language = <[ISO_639-1::en]>

description
    lifecycle_state = <"unmanaged">

definition
    OBSERVATION[id1] matches {    -- Parent
        data matches {
            HISTORY[id2] matches {
                events matches {
                    POINT_EVENT[id3] matches {    -- Point event
                        data matches {
                            ITEM_TREE[id4] matches {
                                items matches {
                                    ELEMENT[id5] -- Score
                                }
                            }
                        }
                    }
                }
            }
        }
    }

terminology
    term_definitions = <
        ["en"] = <
            ["id1"] = <
                text = <"Parent">
                description = <"Parent">
            >
            ["id3"] = <
                text = <"Point event">
                description = <"Point event">
            >
            ["id5"] = <
                text = <"Score">
                description = <"Score">
            >
        >
    >
```

Child archetype:
```
archetype (adl_version=2.0.5; rm_release=1.0.4)
    openEHR-EHR-OBSERVATION.child.v1.0.0

specialize
    openEHR-EHR-OBSERVATION.parent.v1.0.0

language
    original_language = <[ISO_639-1::en]>

description
    lifecycle_state = <"unmanaged">

definition
    OBSERVATION[id1.1] matches {    -- Child
        /data[id2]/events[id3]/data[id4]/items matches {
            ELEMENT[id5.1] occurrences matches {0..1} matches {  -- Pain score
                 value matches {
                     DV_ORDINAL[id0.1] matches {
                         [value, symbol] matches {
                             [{1}, {[at0.1]}],
                             [{2}, {[at0.2]}],
                             [{3}, {[at0.3]}]
                         }
                     }
                 }
            }
        }
    }

terminology
    term_definitions = <
        ["en"] = <
            ["id1.1"] = <
                text = <"Child">
                description = <"Child">
            >
            ["id5.1"] = <
                text = <"Score">
                description = <"Score">
            >
            ["ac7.1"] = <
                text = <"Score valueset">
                description = <"Score valueset">
            >
            ["at0.1"] = <
                text = <"One">
                description = <"One">
            >
            ["at0.2"] = <
                text = <"Two">
                description = <"Two">
            >
            ["at0.3"] = <
                text = <"Three">
                description = <"Three">
            >
        >
    >
    value_sets = <
        ["ac7.1"] = <
            id = <"ac7.1">
            members = <"at0.1", "at0.2", "at0.3">
        >
    >
```

**Comment by pieterbos** [comment]
fixed.
